CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(100) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name  VARCHAR(100),
    phone      VARCHAR(30),
    is_active  BOOLEAN      NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

-- delete user should be able to create a new account
-- CREATE UNIQUE INDEX uq_users_email_active ON users (email) WHERE deleted_at IS NULL;
-- CREATE UNIQUE INDEX uq_users_username_active ON users (username) WHERE deleted_at IS NULL;

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE countries
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE cities
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(40)  NOT NULL UNIQUE,
    name       VARCHAR(100) NOT NULL,
    country_id BIGINT REFERENCES countries (id)
);

CREATE TABLE municipalities
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(40)  NOT NULL UNIQUE,
    name       VARCHAR(100) NOT NULL,
    city_id BIGINT REFERENCES cities (id)
);

CREATE TABLE pet_species
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE pet_breeds
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(60)  NOT NULL UNIQUE,
    name       VARCHAR(100) NOT NULL,
    species_id BIGINT       NOT NULL REFERENCES pet_species (id)
);

CREATE TABLE business_types
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE listing_statuses
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE application_statuses
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE businesses
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id         BIGINT       NOT NULL REFERENCES business_types (id),
    name            VARCHAR(150) NOT NULL,
    description     TEXT,
    phone           VARCHAR(30)  NOT NULL,
    email           VARCHAR(255),
    address         VARCHAR(255) NOT NULL,
    municipality_id BIGINT       NOT NULL REFERENCES municipalities (id),
    owner_id        BIGINT REFERENCES users (id),
    latitude        DECIMAL(9, 6),
    longitude       DECIMAL(9, 6),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE TABLE pets
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(100) NOT NULL,
    species_id           BIGINT       NOT NULL REFERENCES pet_species (id),
    age                  BIGINT,
    gender               VARCHAR(10)  NOT NULL,
    size                 VARCHAR(10),
    birth_date           DATE,
    weight_kg            DECIMAL(5, 2),
    description          TEXT,
    good_with_kids       BOOLEAN      NOT NULL DEFAULT false,
    good_with_other_pets BOOLEAN      NOT NULL DEFAULT false,
    CONSTRAINT check_pet_gender CHECK (gender IN ('MALE', 'FEMALE', 'UNKNOWN')),
    CONSTRAINT check_pet_size CHECK (size IN ('SMALL', 'MEDIUM', 'LARGE')
        )
);

CREATE TABLE pet_breed_links
(
    pet_id   BIGINT NOT NULL REFERENCES pets (id) ON DELETE CASCADE,
    breed_id BIGINT NOT NULL REFERENCES pet_breeds (id),
    PRIMARY KEY (pet_id, breed_id)
);

CREATE TABLE pet_photos
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id        BIGINT       NOT NULL REFERENCES pets (id) ON DELETE CASCADE,
    url           VARCHAR(500) NOT NULL,
    is_primary    BOOLEAN      NOT NULL DEFAULT false,
    display_order INT          NOT NULL DEFAULT 0
);

CREATE TABLE listings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id          BIGINT         NOT NULL REFERENCES pets (id),
    posted_by       BIGINT         NOT NULL REFERENCES users (id),
    business_id     BIGINT REFERENCES businesses (id),
    municipality_id BIGINT         NOT NULL REFERENCES municipalities (id),
    status_id       BIGINT         NOT NULL REFERENCES listing_statuses (id),
    title           VARCHAR(150),
    description     TEXT,
    adoption_fee    DECIMAL(10, 2) NOT NULL DEFAULT 0,
    latitude        DECIMAL(9, 6),
    longitude       DECIMAL(9, 6),
    expires_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE TABLE adoption_applications
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id    BIGINT      NOT NULL REFERENCES listings (id),
    applicant_id  BIGINT      NOT NULL REFERENCES users (id),
    status_id     BIGINT      NOT NULL REFERENCES application_statuses (id),
    message       TEXT,
    contact_phone VARCHAR(30),
    contact_email VARCHAR(255),
    reviewed_by   BIGINT REFERENCES users (id),
    reviewed_at   TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);
