CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(100) UNIQUE NOT NULL,
    email      VARCHAR(255) UNIQUE NOT NULL,
    password   VARCHAR(255)        NOT NULL,
    created_at TIMESTAMP           NOT NULL DEFAULT now(),
    updated_at TIMESTAMP           NOT NULL DEFAULT now()
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE municipalities
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL DEFAULT 'Skopje'
);

INSERT INTO municipalities (code, name)
VALUES ('AERODROM', 'Aerodrom'),
       ('BUTEL', 'Butel'),
       ('CENTAR', 'Centar'),
       ('CAIR', 'Čair'),
       ('GAZI_BABA', 'Gazi Baba'),
       ('GJORCE_PETROV', 'Gjorče Petrov'),
       ('KARPOS', 'Karpoš'),
       ('KISELA_VODA', 'Kisela Voda'),
       ('SARAJ', 'Saraj'),
       ('SUTO_ORIZARI', 'Šuto Orizari');

CREATE TABLE pets
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(100) NOT NULL,
    species              VARCHAR(30)  NOT NULL,
    breed                VARCHAR(100),
    gender               VARCHAR(10)  NOT NULL,
    size                 VARCHAR(10),
    birth_date           DATE,
    good_with_kids       BOOLEAN      NOT NULL DEFAULT false,
    good_with_other_pets BOOLEAN      NOT NULL DEFAULT false,
    description          TEXT,
    municipality_id      BIGINT       NOT NULL REFERENCES municipalities (id),
    photo_url            VARCHAR(500),
    status               VARCHAR(20)  NOT NULL DEFAULT 'AVAILABLE',
    posted_by            BIGINT       NOT NULL REFERENCES users (id),
    created_at           TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT check_pet_species CHECK (species IN ('DOG', 'CAT', 'RABBIT', 'BIRD', 'OTHER')),
    CONSTRAINT check_pet_gender CHECK (gender IN ('MALE', 'FEMALE', 'UNKNOWN')),
    CONSTRAINT check_pet_size CHECK (size IN ('SMALL', 'MEDIUM', 'LARGE')),
    CONSTRAINT check_pet_status CHECK (status IN ('AVAILABLE', 'PENDING', 'ADOPTED'))
);

CREATE TABLE businesses
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            VARCHAR(20)  NOT NULL,
    name            VARCHAR(150) NOT NULL,
    description     TEXT,
    phone           VARCHAR(30)  NOT NULL,
    email           VARCHAR(255),
    address         VARCHAR(255) NOT NULL,
    municipality_id BIGINT       NOT NULL REFERENCES municipalities (id),
    owner_id        BIGINT REFERENCES users (id),
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT check_business_type CHECK (type IN ('VET', 'GROOMER', 'PET_SHOP'))
);

CREATE TABLE business_hours
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT   NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL,
    open_time   TIME,
    close_time  TIME,
    closed      BOOLEAN  NOT NULL DEFAULT false,
    CONSTRAINT check_day_of_week CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT unique_business_day UNIQUE (business_id, day_of_week)
);

CREATE TABLE reviews
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT    NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    user_id     BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    rating      SMALLINT  NOT NULL,
    comment     TEXT,
    created_at  TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT check_review_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT unique_review_per_user UNIQUE (business_id, user_id)
);

CREATE TABLE bookings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT      NOT NULL REFERENCES businesses (id) ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    start_time  TIMESTAMP   NOT NULL,
    end_time    TIMESTAMP   NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    notes       TEXT,
    created_at  TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT check_booking_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT check_booking_time CHECK (end_time > start_time)
);

INSERT INTO roles (name)
VALUES ('USER'),
       ('BUSINESS'),
       ('ADMIN');

CREATE INDEX idx_pets_species ON pets (species);
CREATE INDEX idx_pets_status ON pets (status);
CREATE INDEX idx_businesses_type ON businesses (type);
CREATE INDEX idx_pets_municipality ON pets (municipality_id);
CREATE INDEX idx_businesses_municipality ON businesses (municipality_id);
CREATE INDEX idx_reviews_business ON reviews (business_id);
CREATE INDEX idx_bookings_biz_time ON bookings (business_id, start_time);