CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(100) UNIQUE NOT NULL,
    email      VARCHAR(255) UNIQUE NOT NULL,
    password   VARCHAR(255)        NOT NULL,
    created_at TIMESTAMP           NOT NULL DEFAULT now(),
    updated_at TIMESTAMP           NOT NULL DEFAULT now()
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE municipalities
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL DEFAULT 'Skopje'
);

CREATE TABLE pet_species
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE pet_breeds
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(60)  NOT NULL UNIQUE,
    name       VARCHAR(100) NOT NULL,
    species_id BIGINT       NOT NULL REFERENCES pet_species (id)
);

CREATE TABLE business_types
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE listing_statuses
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40)  NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE pets
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(100) NOT NULL,
    species_id           BIGINT       NOT NULL REFERENCES pet_species (id),
    gender               VARCHAR(10)  NOT NULL,
    size                 VARCHAR(10),
    birth_date           DATE,
    good_with_kids       BOOLEAN      NOT NULL DEFAULT false,
    good_with_other_pets BOOLEAN      NOT NULL DEFAULT false,
    created_at           TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT check_pet_gender CHECK (gender IN ('MALE', 'FEMALE', 'UNKNOWN')),
    CONSTRAINT check_pet_size CHECK (size IN ('SMALL', 'MEDIUM', 'LARGE'))
);

CREATE TABLE pet_breed_links
(
    pet_id   BIGINT NOT NULL REFERENCES pets (id) ON DELETE CASCADE,
    breed_id BIGINT NOT NULL REFERENCES pet_breeds (id),
    PRIMARY KEY (pet_id, breed_id)
);

CREATE TABLE pet_photos
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id     BIGINT       NOT NULL REFERENCES pets (id) ON DELETE CASCADE,
    url        VARCHAR(500) NOT NULL,
    is_primary BOOLEAN      NOT NULL DEFAULT false
);

CREATE TABLE businesses
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id         BIGINT       NOT NULL REFERENCES business_types (id),
    name            VARCHAR(150) NOT NULL,
    description     TEXT,
    phone           VARCHAR(30)  NOT NULL,
    email           VARCHAR(255),
    address         VARCHAR(255) NOT NULL,
    municipality_id BIGINT       NOT NULL REFERENCES municipalities (id),
    owner_id        BIGINT REFERENCES users (id),
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE listings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id          BIGINT    NOT NULL REFERENCES pets (id),
    posted_by       BIGINT    NOT NULL REFERENCES users (id),
    municipality_id BIGINT    NOT NULL REFERENCES municipalities (id),
    status_id       BIGINT    NOT NULL REFERENCES listing_statuses (id),
    description     TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP NOT NULL DEFAULT now()
);

INSERT INTO roles (name)
VALUES ('USER'),
       ('BUSINESS'),
       ('ADMIN');

INSERT INTO municipalities (code, name)
VALUES ('AERODROM', 'Aerodrom'),
       ('BUTEL', 'Butel'),
       ('CENTAR', 'Centar'),
       ('CAIR', 'Čair'),
       ('GAZI_BABA', 'Gazi Baba'),
       ('GJORCE_PETROV', 'Gjorče Petrov'),
       ('KARPOS', 'Karpoš'),
       ('KISELA_VODA', 'Kisela Voda'),
       ('SARAJ', 'Saraj'),
       ('SUTO_ORIZARI', 'Šuto Orizari');

INSERT INTO pet_species (code, name)
VALUES ('DOG', 'Dog'),
       ('CAT', 'Cat'),
       ('RABBIT', 'Rabbit'),
       ('BIRD', 'Bird'),
       ('OTHER', 'Other');

INSERT INTO business_types (code, name)
VALUES ('VET', 'Veterinary Clinic'),
       ('GROOMER', 'Groomer'),
       ('PET_SHOP', 'Pet Shop');

INSERT INTO listing_statuses (code, name)
VALUES ('AVAILABLE', 'Available'),
       ('PENDING', 'Pending'),
       ('ADOPTED', 'Adopted');