
PETS = [
    # ---------------- DOGS ----------------
    {
        "id": "dog_labrador",
        "species_code": "DOG",
        "breed_code": "LABRADOR",
        "name": "Labrador Retriever",
        "space_needed": "large",
        "maintenance": "high",
        "good_with_kids": True,
        "good_with_other_pets": True,
        "needs_yard": True,
        "time_commitment": "high",
        "lifespan_years": 11,
        "cost_per_month": 100,
        "shedding": "high",
        "noise_level": "medium",
        "exercise_needs": "high",
        "social_needs": "high",
        "training_difficulty": "easy",
        "allergenic": True,
        "climate_preference": "flexible",
        "description": "Friendly, athletic family dog. Needs a yard and daily exercise. One of the most commonly surrendered/adopted breeds at shelters.",
    },
    {
        "id": "dog_german_shepherd",
        "species_code": "DOG",
        "breed_code": "GERMAN_SHEPHERD",
        "name": "German Shepherd",
        "space_needed": "large",
        "maintenance": "high",
        "good_with_kids": True,
        "good_with_other_pets": False,
        "needs_yard": True,
        "time_commitment": "high",
        "lifespan_years": 10,
        "cost_per_month": 120,
        "shedding": "high",
        "noise_level": "medium",
        "exercise_needs": "high",
        "social_needs": "medium",
        "training_difficulty": "difficult",
        "allergenic": True,
        "climate_preference": "flexible",
        "description": "Loyal, intelligent, protective. Needs an experienced owner, consistent training, and daily mental/physical activity.",
    },
    {
        "id": "dog_golden_retriever",
        "species_code": "DOG",
        "breed_code": "GOLDEN_RETRIEVER",
        "name": "Golden Retriever",
        "space_needed": "large",
        "maintenance": "high",
        "good_with_kids": True,
        "good_with_other_pets": True,
        "needs_yard": True,
        "time_commitment": "high",
        "lifespan_years": 11,
        "cost_per_month": 110,
        "shedding": "high",
        "noise_level": "low",
        "exercise_needs": "high",
        "social_needs": "high",
        "training_difficulty": "easy",
        "allergenic": True,
        "climate_preference": "flexible",
        "description": "Gentle, patient, great with families. Heavy shedder that needs regular grooming plus daily exercise.",
    },
    {
        "id": "dog_bulldog",
        "species_code": "DOG",
        "breed_code": "BULLDOG",
        "name": "Bulldog",
        "space_needed": "small",
        "maintenance": "medium",
        "good_with_kids": True,
        "good_with_other_pets": True,
        "needs_yard": False,
        "time_commitment": "medium",
        "lifespan_years": 9,
        "cost_per_month": 90,
        "shedding": "medium",
        "noise_level": "low",
        "exercise_needs": "low",
        "social_needs": "medium",
        "training_difficulty": "moderate",
        "allergenic": True,
        "climate_preference": "temperate",
        "description": "Calm, low-exercise, apartment-friendly. Prone to breathing/joint issues, so vet costs tend to run higher than average.",
    },
    {
        "id": "dog_poodle",
        "species_code": "DOG",
        "breed_code": "POODLE",
        "name": "Poodle",
        "space_needed": "medium",
        "maintenance": "high",
        "good_with_kids": True,
        "good_with_other_pets": True,
        "needs_yard": False,
        "time_commitment": "medium",
        "lifespan_years": 14,
        "cost_per_month": 90,
        "shedding": "low",
        "noise_level": "medium",
        "exercise_needs": "medium",
        "social_needs": "high",
        "training_difficulty": "easy",
        "allergenic": False,
        "climate_preference": "flexible",
        "description": "Highly intelligent, hypoallergenic coat, easy to train. Needs regular professional grooming.",
    },
    {
        "id": "dog_mixed",
        "species_code": "DOG",
        "breed_code": "MIXED",
        "name": "Mixed Breed Dog",
        "space_needed": "medium",
        "maintenance": "medium",
        "good_with_kids": True,
        "good_with_other_pets": True,
        "needs_yard": False,
        "time_commitment": "medium",
        "lifespan_years": 13,
        "cost_per_month": 70,
        "shedding": "medium",
        "noise_level": "medium",
        "exercise_needs": "medium",
        "social_needs": "medium",
        "training_difficulty": "moderate",
        "allergenic": True,
        "climate_preference": "flexible",
        "description": "The most common shelter dog. Traits vary by individual, but generally hardier and more moderate across the board than purebreds. Ask the shelter about the specific dog's temperament.",
    },

    # ---------------- CATS ----------------
    {
        "id": "cat_persian",
        "species_code": "CAT",
        "breed_code": "PERSIAN",
        "name": "Persian",
        "space_needed": "small",
        "maintenance": "high",
        "good_with_kids": True,
        "good_with_other_pets": True,
        "needs_yard": False,
        "time_commitment": "medium",
        "lifespan_years": 15,
        "cost_per_month": 55,
        "shedding": "high",
        "noise_level": "low",
        "exercise_needs": "low",
        "social_needs": "medium",
        "training_difficulty": "easy",
        "allergenic": True,
        "climate_preference": "flexible",
        "description": "Calm, quiet lap cat. Long coat needs daily brushing to avoid matting; more grooming upkeep than most cats.",
    },
    {
        "id": "cat_siamese",
        "species_code": "CAT",
        "breed_code": "SIAMESE",
        "name": "Siamese",
        "space_needed": "small",
        "maintenance": "low",
        "good_with_kids": True,
        "good_with_other_pets": True,
        "needs_yard": False,
        "time_commitment": "medium",
        "lifespan_years": 18,
        "cost_per_month": 50,
        "shedding": "low",
        "noise_level": "high",
        "exercise_needs": "medium",
        "social_needs": "high",
        "training_difficulty": "easy",
        "allergenic": False,
        "climate_preference": "flexible",
        "description": "Vocal, social, forms strong attachment to owners. Low grooming needs but wants a lot of interaction — not ideal if left alone often.",
    },
    {
        "id": "cat_maine_coon",
        "species_code": "CAT",
        "breed_code": "MAINE_COON",
        "name": "Maine Coon",
        "space_needed": "medium",
        "maintenance": "medium",
        "good_with_kids": True,
        "good_with_other_pets": True,
        "needs_yard": False,
        "time_commitment": "medium",
        "lifespan_years": 13,
        "cost_per_month": 65,
        "shedding": "high",
        "noise_level": "low",
        "exercise_needs": "medium",
        "social_needs": "medium",
        "training_difficulty": "easy",
        "allergenic": True,
        "climate_preference": "cold",
        "description": "Large, friendly, dog-like personality. Needs more space than an average cat and regular brushing for its thick coat.",
    },
    {
        "id": "cat_ragdoll",
        "species_code": "CAT",
        "breed_code": "RAGDOLL",
        "name": "Ragdoll",
        "space_needed": "small",
        "maintenance": "medium",
        "good_with_kids": True,
        "good_with_other_pets": True,
        "needs_yard": False,
        "time_commitment": "medium",
        "lifespan_years": 17,
        "cost_per_month": 60,
        "shedding": "high",
        "noise_level": "low",
        "exercise_needs": "low",
        "social_needs": "high",
        "training_difficulty": "easy",
        "allergenic": True,
        "climate_preference": "flexible",
        "description": "Docile, affectionate, goes limp when held. Follows owners around the house; not well suited to being left alone for long stretches.",
    },
    {
        "id": "cat_mixed",
        "species_code": "CAT",
        "breed_code": "MIXED_CAT",
        "name": "Mixed Breed Cat",
        "space_needed": "small",
        "maintenance": "low",
        "good_with_kids": True,
        "good_with_other_pets": True,
        "needs_yard": False,
        "time_commitment": "low",
        "lifespan_years": 15,
        "cost_per_month": 40,
        "shedding": "medium",
        "noise_level": "low",
        "exercise_needs": "low",
        "social_needs": "medium",
        "training_difficulty": "easy",
        "allergenic": True,
        "climate_preference": "flexible",
        "description": "The most common shelter cat. Independent, low-maintenance, adapts well to apartments. Individual temperament varies — ask the shelter.",
    },

    # ---------------- OTHER SPECIES (no breed table) ----------------
    {
        "id": "rabbit_general",
        "species_code": "RABBIT",
        "breed_code": None,
        "name": "Rabbit",
        "space_needed": "medium",
        "maintenance": "medium",
        "good_with_kids": True,
        "good_with_other_pets": True,
        "needs_yard": False,
        "time_commitment": "medium",
        "lifespan_years": 9,
        "cost_per_month": 45,
        "shedding": "high",
        "noise_level": "low",
        "exercise_needs": "medium",
        "social_needs": "high",
        "training_difficulty": "moderate",
        "allergenic": True,
        "climate_preference": "temperate",
        "description": "Social, litter-trainable, needs a secure hutch or bunny-proofed space plus daily out-of-cage time. Commonly available at shelters.",
    },
    {
        "id": "bird_general",
        "species_code": "BIRD",
        "breed_code": None,
        "name": "Bird (Budgie / Parakeet type)",
        "space_needed": "small",
        "maintenance": "low",
        "good_with_kids": True,
        "good_with_other_pets": False,
        "needs_yard": False,
        "time_commitment": "medium",
        "lifespan_years": 8,
        "cost_per_month": 30,
        "shedding": "medium",
        "noise_level": "medium",
        "exercise_needs": "low",
        "social_needs": "high",
        "training_difficulty": "easy",
        "allergenic": False,
        "climate_preference": "flexible",
        "description": "Small, social cage bird. Apartment-friendly and low-cost, but needs daily interaction and out-of-cage time.",
    },
    {
        "id": "reptile_general",
        "species_code": "REPTILE",
        "breed_code": None,
        "name": "Reptile (Bearded Dragon type)",
        "space_needed": "medium",
        "maintenance": "medium",
        "good_with_kids": False,
        "good_with_other_pets": False,
        "needs_yard": False,
        "time_commitment": "low",
        "lifespan_years": 10,
        "cost_per_month": 55,
        "shedding": "low",
        "noise_level": "low",
        "exercise_needs": "low",
        "social_needs": "low",
        "training_difficulty": "moderate",
        "allergenic": False,
        "climate_preference": "tropical",
        "description": "Low daily interaction but needs proper heat/UVB lighting setup and live-insect feeding. Kids should only handle with supervision.",
    },
    {
        "id": "small_mammal_general",
        "species_code": "SMALL_MAMMAL",
        "breed_code": None,
        "name": "Small Mammal (Guinea Pig type)",
        "space_needed": "small",
        "maintenance": "low",
        "good_with_kids": True,
        "good_with_other_pets": True,
        "needs_yard": False,
        "time_commitment": "low",
        "lifespan_years": 6,
        "cost_per_month": 30,
        "shedding": "medium",
        "noise_level": "low",
        "exercise_needs": "low",
        "social_needs": "high",
        "training_difficulty": "easy",
        "allergenic": True,
        "climate_preference": "temperate",
        "description": "Great starter pet for kids. Low cost and low daily time commitment, but happiest kept in pairs and needs cage cleaning a few times a week.",
    },
]

PET_BY_ID = {pet["id"]: pet for pet in PETS}

PETS_BY_SPECIES: dict[str, list[dict]] = {}
for _pet in PETS:
    PETS_BY_SPECIES.setdefault(_pet["species_code"], []).append(_pet)